### ISSUE TITLE
telemetry(metric,log,trace)를 전달할 Collector가 필요한가?

### ISSUE THREAD

**Issue by bohub12** [bohub12/metrics-monitoring-sample#4]
## 참고링크
- [Do you need an OpenTelemetry Collector? | Grafana Labs](https://grafana.com/blog/2023/11/21/do-you-need-an-opentelemetry-collector/)

---

많은 레퍼런스를 보면, Grafana - OpenTelemetry를 같이 사용해서 구축하고 있다. 이 방식이 왜 많이 사용되고 추천되고 사용되는지 알아보자. 굳이 필요한 것인가에 대한 고민도 해보자.

> 용어 설명
- `telemetry` = logs, metrics, and traces

![image](https://github.com/user-attachments/assets/db3b8c9c-f5a0-4b71-b1a9-afb9f0659b63)

많은 예제 및 레퍼런스는 위와 같은 구조를 띈다. 중간의 collector 는 중간에서 application 혹은 infra에서 발생하는 telemetry를 받아서 storage 로 전송한다.

이런 모델을 `collector model` 이라고 하는데, 이는 telemetry 측면에서는 일반적인 모델이라고 한다.

**하지만! collector를 통하지 않고, 직접 backend(storage)로 telemetry를 전송하면 안되는 것인가?**

- `OTel SDK`를 구성하면, `OTLP` (OpenTelemetry Protocol)를 이용해서 직접 telemetry를 전송해주는 건 가능하다.

```bash
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-east-0.grafana.net/otlp
HEADER="Basic $(echo -n $GRAFANA_INSTANCE_ID:$TOKEN | base64)"
OTEL_EXPORTER_OTLP_HEADERS="Authorization=$HEADER"
OTEL_TRACES_EXPORTER=otlp
OTEL_METRICS_EXPORTER=otlp
OTEL_LOGS_EXPORTER=otlp
OTEL_SERVICE_NAME="my-cool-service"
```

위처럼 구성해주면, collector 없이도 구성이 가능하다. 하지만 프로덕션 환경에선 중간에 collector를 둬야하는 여러 이유가 있다.

# Collector model 이 필요한 이유
## 1. filtering sensitive data

많은 서비스에선 민감한 유저의 정보(주민번호, 카드번호 등등)을 가지고 있다.

만약 collector 없이 바로 backend로 telemetry를 전송하게 된다면, Grafana에 접근할 수 있는 누구든지 해당 정보들을 확인할 수 있게 된다

- 즉, telemetry 를 전송하기전에 `전처리(preprocessing)` 과정이 필요하다

아래처럼 민감한 정보들을 숨길 수 있다

```yaml
processors:
  transform/redact_info:
    error_mode: ignore
    log_statements:
    - context: log
      statements:
      - replace_all_matches(attributes, "secret_value", "********")

service:
  pipelines:
    logs:
      receivers: [...]
      processors: [transform/redact_info, abc]
      exporters: [...]
```

## 2. managing cost

그라파나는 수집된 데이터의 GB 단위로 비용을 청구한다고 한다. 만약 collector를 쓴다면 중간에서 불필요한 telemetry는 전송하지 않음으로써 비용을 절감할 수 있다.

## 3. decoupling

처음에는 collector를 통하지 않고 직접 telemetry를 전송하는 것이 편할 수 있다. 만약 많은 Grafana OSS 를 사용하고 있다면 여러 endpoint가 관측 대상이 되는 어플리케이션에서 관리되고 있는 구조가 된다. 

하지만, 만약 많은 시스템 중 한 모니터링 시스템의 endpoint가 변경되면 어플리케이션을 재배포해야한다. 

그렇기에, 최대한 Grafana OSS 와의 의존성을 없애고 collector에서 여러 Grafana OSS를 관리하도록 해주는 것이 좋다.
